config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, except: [:new]
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 12, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25}
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save {  self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
            uniqueness: true,
            length: {minimum: 3, maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            uniqueness: true,
            format: {with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "you can only edit or delete your own article"
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "success"
      redirect_to @category
    else
      render 'new'
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in"
      redirect_to user
    else
      flash.now[:alert] = "Invalid"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 2)
  end

  def index
    @users = User.paginate(page: params[:page], per_page:5)
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Your account was updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome, you have successfully signed up"
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "account deleted"
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit your own account"
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user)
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}"
    image_tag(gravatar_url, alt: user.username)
  end



end

app/views/articles/_article.html.erb
<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th colspan="3">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <% if article.user %>
        <td>by: <%= link_to article.user.username, user_path(article.user) %></td>
      <% end %>
      <td><%= article.description %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <% if logged_in? && article.user == current_user || current_user.admin? %>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= button_to 'Delete', article_path(article), method: :delete, onclick: "return confirm('Are you sure')" %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<p>
  <%= link_to 'Create new article', new_article_path %>
</p>

app/views/articles/edit.html.erb
<h1>Edit This Article</h1>
<%= render 'shared/errors', obj: @article %>

<%= render 'layouts/form' %>
  <p>
    <%= link_to 'Cancel and Return to articles listing', articles_path %>
  </p>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<%= will_paginate @articles %>

<%= render 'article' %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>
<%= render 'shared/errors', obj: @article %>

<%= render 'layouts/form' %>
  <p>
    <%= link_to 'Return to articles listing', articles_path %>
  </p>

app/views/articles/show.html.erb
<h1>Showing article details</h1>
<h2>Title: <%= @article.title %></h2>
<p>By: <%= @article.user.username if @article.user %></p>
<p>Desc: <%= @article.description %></p>
<%if @article.categories.any? %>
<p>Categories: <%= render @article.categories %></p>
<% end %>
<% if logged_in? && (@article.user == current_user || current_user.admin?) %>
  <%= link_to 'Edit', edit_article_path(@article) %> |
  <%= button_to 'Delete', article_path(@article), method: :delete, onclick: "return confirm('Are you sure?')" %> |
<% end %>
<%= link_to 'Return to all articles', articles_path %>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category)%>

app/views/categories/index.html.erb
<h1>Categories</h1>
<%= will_paginate @categories %>
<table>
  <thead>
  <tr>
    <th>name</th>
  </tr>
  </thead>
  <tbody>
  <% @categories.each do |category| %>
    <tr>
      <td>
        <%= link_to category.name, category_path(category) %>
        <p><%= pluralize(category.articles.count, "article") %></p>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<p>
  <%= link_to 'Create new article', new_article_path %>
</p>

app/views/categories/new.html.erb
<h1>Create a new category</h1>

<%= render 'shared/errors', obj: @category %>

<%= form_with(model: @category) do |f| %>
  <p>
    <%= f.label :name, "Category Name" %><br/>
    <%=f.text_field :name, placeholder: "Enter Category Name" %>
  </p>
  <p>
    <%=f.submit "Add Category" %>
  </p>
<% end %>

<div>
  <%= link_to ' [Cancel and return to articles listing ]', articles_path %>
</div>

app/views/categories/show.html.erb
<h1>Category: <%= @category.name %></h1>

<% @category.articles.each do |a| %>
  <%= a.title %>
<% end %>

app/views/layouts/_form.html.erb
<% if @article.errors.any? %>
  <h2>The following Errors have occured</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li>
        <%= msg %>
      </li>
    <%end %>
  </ul>
<% end %>

<%= form_with(model: @article, local: true) do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%=f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :category_ids, "Categories" %><br/>
    <%= f.collection_select(:category_ids, Category.all, :id, :name, {prompt: 'Please Select all that apply (can be empty) '}, {multiple: true, size: 7})%>
  </p>
  <p>
    <%=f.submit %>
  </p>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/_nav.html.erb
<header style="display: flex; width: 100%">
  <ul style="text-decoration: none; list-style: none; display: flex; flex: 1; justify-content: flex-end;">
    <% if logged_in? %>
      <li>
        <%= "(Admin)" if current_user.admin? %><%= current_user.username %>
      </li>
    <% end %>
    <% if logged_in? && current_user.admin? %>
      <li>
        <%= link_to 'Create New Category', new_category_path %>
      </li>
    <% end %>
    <li>
      <%= "(Admin)" if current_user.admin? %><%= current_user.username %>
    </li>
    <li>
      <%= link_to 'Articles listing', articles_path %> |
    </li>
    <li>
      <%= link_to 'About', about_path %>
    </li>
    <% if logged_in? %>
      <li>
        <%= button_to 'Log Out', logout_path, method: :delete %> |
      </li>
    <% else %>
      <li>
        <%= link_to 'Log In', login_path %> |
      </li>
    <% end %>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewAlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
  <%= render 'layouts/nav' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<%= link_to 'Articles listing', articles_path %> |
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<h1>Hello Ruby</h1>

<% if logged_in? %>
  <%= button_to 'Log Out', logout_path, method: :delete %> |
<% else %>
  <%= link_to 'Log In', login_path %> |
<% end %>
<%= link_to 'Articles listing', articles_path %> |
<%= link_to 'About', about_path %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div>
    <h4>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </h4>
  </div>
<%end %>

app/views/shared/errors.html.erb
<% if @obj.errors.any %>
  <div>
    <h4>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </h4>
  </div>
<%end %>

app/views/users/_form.html.erb
<%#= render 'shared/errors', obj: @user %>

<%= form_with(model: @user) do |f| %>
  <p>
    <%= f.label :username %><br/>
    <%=f.text_field :username, placeholder: "Enter Username" %>
  </p>
  <p>
    <%= f.label :email %><br/>
    <%= f.email_field :email, placeholder: "Enter Email Address" %>
  </p>
  <p>
    <%= f.label :password %><br/>
    <%= f.password_field :password, placeholder: "Enter Password" %>
  </p>
  <p>
    <%=f.submit(@user.new_record? ? "Sign Up": "Update account") %>
  </p>
<% end %>

<div>
  <%= link_to ' [Cancel and return to articles listing ]', articles_path %>
</div>

app/views/users/edit.html.erb
<h1>edit profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>All Users</h1>

<%= will_paginate @users %>

<% @users.each do |user| %>
  <p>Username:<%= link_to user.username, user %></p>
  <p>Joined <%= time_ago_in_words(user.created_at) %> ago</p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s profile</h1>

<%= gravatar_for @user %>

<div>
  <% if logged_in? && (@user == current_user || current_user.admin?) %>
    <%= link_to "Edit your profile", edit_user_path(@user) %>
    <%= button_to "Delete account", user_path(@user), method: :delete, onclick: "return confirm('Are you sure?')" %>
  <% end %>
</div>
<br/>
<%= will_paginate @articles %>

<%= render 'articles/article' %>